---
roles:
  - name: geerlingguy.docker
    version: 4.1.3
  - name: Install aws-cli
    role: deekayen.awscli2
    version: 1.1.0
  - name: Install terraform
    role: diodonfrost.terraform
    version: 1.6.1